### ISSUE TITLE
Use user language as default language to download subtitles example ENV['lang'] 

### ISSUE THREAD

**Issue by evandrojr** [evandrojr/layback#1]

**Comment by marcelobarreto** [comment]
I'm working on it :smile:

**Comment by evandrojr** [comment]
Great!

**Comment by marcelobarreto** [comment]
Do you think that worth work on that? For example, I use my computer in english, but when watching movies, I would like to grab my subtitles in pob(brazilian portuguese).

**Comment by evandrojr** [comment]
I am the opposite of you. My pc is set to pt-br but I rather use English
subtitles lol. I only use pob when my wife is around.

​​
I think the priority is support for Plex media center. Since it is very
well known. Many people are using it including myself. Which one do you
use? Do you stream movies to TV?

**Comment by marcelobarreto** [comment]
I've used PS3 media server once.
